### ISSUE TITLE
crash with ui5 and xbmc 11

### ISSUE THREAD

**Issue by mbaillargeon** [gderosa/xbmc-vera#1]
When I try to access the device status "ex: light" xbmc crash

**Comment by cw-kid** [comment]
I have tried this add-on with XBMC 12 (Frodo), XBMC 13 (Gotham) and Kodi 14 (Helix) and it has never crashed XBMC out. Maybe this was just an issue with XBMC 11 (Eden) ?

**Comment by gderosa** [comment]
Original bug report from @mbaillargeon is three years old now.

@mbaillargeon, can you provide any updates? @cw-kid, if you confirm the crash doesn't happen with reasonably new releases, we can close this issue.

**Comment by cw-kid** [comment]
Yes I agree close this issue.
