### ISSUE TITLE
Scenes not working property

### ISSUE THREAD

**Issue by Pete44** [gderosa/xbmc-vera#2]
Some scenes are mark not active and you are not able to trigger those. In order to use them, you have to trigger first directly from mios. In my opinion the scene does not have to check if its active or not active in order to let it run.

**Comment by cw-kid** [comment]
I made a work around solution for this issue:

What I did was I just removed one line of code from a file called scene.py located in \xbmc-vera-master\resources\lib\vera

I removed this line:    if scene['active']:

I am now able to run non active scenes OK.

**Comment by cw-kid** [comment]
Here is the original scene.py file contents

![vera-scene py-1](https://cloud.githubusercontent.com/assets/9383216/6865126/a91991ac-d462-11e4-99cd-315228938931.png)

Removing the line:

if scene['active']:

Then allowed me to run none active scenes in the Vera add-on in XBMC. 

Modified scene.py file contents

![vera-scene py-2](https://cloud.githubusercontent.com/assets/9383216/6865143/cb3ff64a-d462-11e4-9afe-f14d748d8718.png)

**Comment by gderosa** [comment]
@cw-kid, in the long term, it might be beneficial if you clone this project, make your changes there and then send me a pull request... in other words: using GitHub properly as a collaborative environment (even if you change just one line of code: a valuable change anyway).

No problem in applying the changes myself for now (as soon as I have a working testing environment) (and thanks a lot for that, by the way!). Just, random ideas for future contributions.

Thanks once again.

**Comment by gderosa** [comment]
@cw-kid thanks for the suggestion and sorry for so late commit/merge.

I've not tested this extensively but I trust your tests.

Let me know if any questions or further issues.

Closing this for now.
