### ISSUE TITLE
Some scenes present not active condition

### ISSUE THREAD

**Issue by Pete44** [gderosa/xbmc-vera#3]
Some scenes present not active condition and can't be triggered from xbmc

**Comment by cw-kid** [comment]
Can you be more descriptive about this problem please? Percent or Present ?

**Comment by gderosa** [comment]
Thanks @cw-kid and @Pete44. Yes, more details please and possibly screenshots. Including: what you have in Vera, and what you see from within kodi.

**Comment by Pete44** [comment]
@cw-kid @gderosa i just found that @cw-kid corrected this problem removing the line if scene not active, im going to test it and let you know how it works.

Thanks
Pete

**Comment by gderosa** [comment]
@Pete44, okay, closiing this isssue for now, let me know if needs to be reopened.
