### ISSUE TITLE
Dependencies not met error when installing add-on

### ISSUE THREAD

**Issue by cw-kid** [gderosa/xbmc-vera#4]
When installing the Vera add-on in XBMC Gotham or Kodi Helix you get a dependencies not met error.

To resolve this the Python version needs to be updated in the addon.xml file.

I changed the version to 2.1.0 and I was able to then install the add-on OK.

<import addon="xbmc.python" version="2.1.0"/>

See this link for more information:

http://kodi.wiki/view/addon.xml#Dependency_versions

**Comment by gderosa** [comment]
@cw-kid, it would be nice if you could share your changes, ideally by creating a fork on GitHub and then sending me a pull request. If you need any help with git, let me know.

As an alternative, althogh not optimal, send me an email with patch / tarball.

Let me know if you have any questions.

**Comment by cw-kid** [comment]
For this issue I only changed one line of code in the addon.xml file.

Change this:

![vera-add-on-xml-1](https://cloud.githubusercontent.com/assets/9383216/6864994/f59e20e4-d460-11e4-99a6-fb6f93cac300.png)

To this:

![vera-add-on-xml-2](https://cloud.githubusercontent.com/assets/9383216/6864998/faf44cda-d460-11e4-9311-b8e2744e7f45.png)

**Comment by gderosa** [comment]
Thanks a lot @cw-kid ! :+1: 

(and the usual advice on using git for the future applies :wink:  )

**Comment by gderosa** [comment]
Sorry for the delay (and this was easy). 
https://github.com/gderosa/xbmc-vera/commit/7b531666422234880d2c285314f704446ad3cbae
